# Generated by Django 2.0.7 on 2018-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180806_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Female'), ('male', 'Male'), ('not-specified', 'Not Specified')], max_length=80, null=True),
        ),
    ]
