# Generated by Django 2.0.7 on 2018-08-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notifications_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at']},
        ),
    ]
