# Generated by Django 2.0.7 on 2018-07-30 11:13
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('images', '0002_auto_20180730_1932'),
    ]
    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='locatio',
            new_name='location',
        ),
    ]
